[package]
name = "calendsync"
version = "0.0.0"
homepage = "https://github.com/cloudbridgeuy/calendsync"
description = "Create calendars to sync with your friends"
autobins = false

authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "calendsync"
path = "src/main.rs"

[dependencies]
