[package]
name = "calendsync_frontend"
version = "0.0.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
build = "build.rs"

[lib]
path = "src/lib.rs"

[build-dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
